name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  call-reusable-ci:
    uses: ./.github/worflows/reusable-ci.yml
    
<<<<<<< HEAD
    steps:
     - name: Setup repository
       uses: ./.github/actions/setup-repo


     - name: Setup Node
       uses: actions/setup-node@v4
       with:
         node-version: '18'

     - name: Install dependencies
       run: npm install

     - name: Build app
       run: npm run build
     
     - name: Run tests
       run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    env:
      APP_ENV: production 
    steps:
     - uses: actions/checkout@v4
     
     - name: Show environment variable
       run: echo "APP_ENV is $APP_ENV"

     - name: 'Deploy to Azure Web App'
       uses: azure/webapps-deploy@v3
       with:
         app-name: 'gha-demo-app'
         slot-name: 'staging'
         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
         package: '.'


=======
>>>>>>> 05b380b (Introduce reusable CI worflow)
